# Generated by Django 2.2.9 on 2020-01-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeApp', '0002_auto_20200118_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
